name: examen-workflow

on: 
  push:
    branches:
      - nueva-caracteristica

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4
      
      - name: Configurar entorno Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar comandos
        run: |
             pip install pytest
             pytest test.py

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build imagen Dockerfile
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: enekoperez/examenModelo
          
